name: Media CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  media-ci:
    if: ${{ github.head_ref != 'alex-up-bot/change-major-version' && github.head_ref != 'alex-up-bot/change-minor-version' && github.head_ref != 'alex-up-bot/change-patch-version' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@7f6df1cd36597249cbf9810ff3aeff47edf8243b

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          pkg-config \
          libcairo2-dev \
          libpango1.0-dev \
          ffmpeg \
          libx11-dev \
          libgl1-mesa-dev \
          fonts-freefont-ttf

      - name: Setup PDM
        run: pip install pdm

      - name: Install Python dependencies
        run: pdm install

      - name: Use PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install JavaScript dependencies
        run: pnpm install

      - name: Run linting checks
        run: pdm run lint

      - name: Install Lato font for Patch It Up artwork
        run: brew install font-lato

      - name: Generate the media files
        run: pdm run generate

      - name: Shorten commit hash for use in media output name
        id: short_hash
        run: echo "short_hash=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Upload the media files to the workflow output
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: media-output_${{ github.ref_name }}_${{ steps.short_hash.outputs.short_hash }}
          path: media

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@dc2d1246a158a1a04045a85a8c1bfd1978afeaf2 # v10.1.0
