name: Media CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  media-ci:
    if: ${{ github.head_ref != 'alex-up-bot/change-major-version' && github.head_ref != 'alex-up-bot/change-minor-version' && github.head_ref != 'alex-up-bot/change-patch-version' }}
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: Setup PDM
        run: pip install pdm

      - name: Install Python dependencies
        run: pdm install --frozen-lockfile

      - name: Setup PNPM
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install JavaScript dependencies
        run: pnpm install

      - name: Run linting checks
        run: pdm run lint

      - name: Run tests
        run: pdm run test

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@d1c2bd1832fa5ae4489ed8f9349676045a683655 # v12.8.0
