name: Restrict alex-up-bot branches

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  restrict-alex-up-bot-branches:
    uses: alextheman231/github-actions/.github/workflows/restrict-alex-up-bot-branches.yml@ec8321ac39e8bc3740a45bab0da66249093fcd8f # v11.0.5
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
