name: Upload media

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  upload:
    if: ${{ github.repository == 'alextheman231/media' }}
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Setup PDM
        run: pip install pdm

      - name: Install Python dependencies
        run: pdm install

      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install JavaScript dependencies
        run: pnpm install

      - name: Clear the existing media folder
        run: rm -rf dist

      - name: Generate the media files
        run: pdm run generate

      - name: Save media cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: dist
          key: media-cache_main_${{ github.sha }}

      - name: Remove cached files from media output
        run: find dist -type d -name partial_movie_files -exec rm -rf {} +

      - name: Shorten commit hash for use in media output name
        id: short_hash
        run: echo "short_hash=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Upload the media files to the workflow output
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: dist
          name: media-output_${{ steps.short_hash.outputs.short_hash }}
